public class Variable {
    public static void main(String[] args) {
        int b=323;
        double c=3.14;
        float d=4.86f;
        boolean e=true;
        char l='$';
        String Song_name="Last_Ride";
        System.out.println("Fav Song: "+Song_name);


    //Swap program
        String x="Moose_Wala";
        String y="Emiway_Bantai";

        String temp;
        temp=x;
        x=y;
        y=temp;
        System.out.println("After Swapping Singers");
        System.out.println("Singer_X: "+x);
        System.out.println("Singer_Y: "+y);

    }

}
